version: "3"
services:
  countryinfos-react-app:
    build: .
    image: countryinfos-react-image
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    environment:
      - WATCHPACK_POLLING=true